config/routes.rb
Rails.application.routes.draw do
#  get 'profiles/show'

  devise_for :users

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    post 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :statuses

  get 'feed', to: 'statuses#index', as: :feed

  root to: 'statuses#index'

  get'/:profile_name', to: 'profiles#show', as: :user_profile


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/status.rb
class Status < ApplicationRecord
	belongs_to :user

	validates :content, presence: true,
	                    length: { minimum: 2 }

	validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true

  validates :last_name, presence: true

  validates :profile_name, presence: true, 
                           uniqueness: true, 
                           format: {
                           	with: /\A[a-zA-Z0-9-_]+\z/,
                           	message: 'has to be formatted correctly or else you cannot use the best app ever!'
                           }

  has_many :statuses, dependent: :destroy

  def full_name
  	first_name + " " + last_name
  end

  def gravatar_url
    stripped_email = email.strip
    downcased_email = stripped_email.downcase 
    hash = Digest::MD5.hexdigest(downcased_email)

    "http://gravatar.com/avatar/#{hash}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	added_attrs = [:first_name, :last_name, :profile_name]
  	devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
  end

  def authenticate_user_custom!
    if user_signed_in?
      authenticate_user!
    else
      redirect_to login_path, :alert => 'You need to log in before you can do that!'
      ## if you want render 404 page
      ## render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_profile_name(params[:profile_name])
  	if @user
  		@statuses = Status.where user_id: @user.id #or @statuses = @user.statuses.all
  		render action: :show
  	else
  	    render file: 'public/404', status: 404, formats: [:html]
  	end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user_custom!, only: [:new, :create, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)
    @status.user_id = current_user.id

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    if @status.user_id == current_user.id
      respond_to do |format|
        if @status.update(status_params)
          format.html { redirect_to @status, notice: 'Status was successfully updated.' }
          format.json { render :show, status: :ok, location: @status }
        else
          format.html { render :edit }
          format.json { render json: @status.errors, status: :unprocessable_entity }
        end
      end
    else 
      respond_to do |format|
        format.html { redirect_to :back, alert: 'You can only edit your own statuses.' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    if @status.user_id == current_user.id
      @status.destroy
      respond_to do |format|
        format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to :back, alert: 'You can only delete your own statuses.' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(type)
    case type
      when 'alert'
      	"alert-danger"
      when 'notice'
      	"alert-success"
      else
      	"alert-warning"
    end
  end
      
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProfilesBook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!--Brand-->
        <%= link_to 'ProfilesBook', feed_path, class: 'navbar-brand' %>
        <!--links-->
        <ul class="nav navbar-nav">
          <li class="nav-item"><%= link_to "All statuses", feed_path %></li>
        </ul>
        <ul class="nav navbar-nav pull-right">
          <% if user_signed_in? %>
            <!--Dropdown menu-->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.full_name %></a>
              <div class="dropdown-menu" aria-labelledby="Preview">
                <%= link_to 'My Profile', user_profile_path(current_user.profile_name), class: 'dropdown-item' %> <br />
                <%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %>
              </div>
            </li>
            <!--End of dropdown menu -->
            <li class="nav-item"><%= link_to "Log Out", logout_path, method: :post %></li>
          <% else %>
            <li class="nav-item"><%= link_to "Register", register_path %></li>
            <li class="nav-item"><%= link_to "Log In", login_path %></li>
          <% end %>
        </ul>   
      </div>
    </div>

    <div class="container">
        <% flash.each do |type, message| %>
          <div class="alert <%= flash_class(type) %>" >
            <button class="close" data-dismiss="alert">&times;</button>
          <%= message %>
        </div>
        <% end %>
        
      <%= yield %>
    </div>

  </body>
</html>

app/views/profiles/show.html.erb
<div class="header">
	<h1><%= @user.full_name %><h1>
</div>

<% if @statuses %>
	<% @statuses.each do |status| %>
	<div class="well">
		<%= status.content %><br />
		<%= link_to time_ago_in_words(status.created_at) + " ago", status %> |
		<%= link_to 'Edit', edit_status_path(status) %> |
		<%= link_to 'Delete', status, method: :delete, data: { confirm: 'You sure?' } %>
	</div>
	<% end %>
<% else %>
    <div>
    	<p>You better start posting some statuses!</p>
    </div>
<% end %>

app/views/statuses/_form.html.erb
<%= simple_form_for(status, html: {:class=>"form-group"} ) do |f| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h3><%= current_user.full_name %>, aka <%= current_user.profile_name %>! Go ahead, illuminate us.</h3>
  <%= f.input :content %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', :back %>

app/views/statuses/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<div class="page-header">
  <h1>All Statuses</h1>
</div>

<%= link_to "Post a New Status", new_status_path, :class => "btn" %>

<% @statuses.each do |status| %>
  <% if status.user != nil %>
    <div class="status">
      <div class="row">

        <div class="col-xs-2">
          <%= image_tag status.user.gravatar_url %>
        </div>

        <div class="col-xs-7">
          <h4><%= status.user.full_name %></h4>
          <p><%= status.content %></p>
          <div class="meta">
            <%= link_to time_ago_in_words(status.created_at) + " ago", status %> |
            <span class="admin">
            <%= link_to "Edit", edit_status_path(status) %> |
            <%= link_to "Delete", status, method: :delete, data: { confirm: "You sure?" } %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <%end %>  
<%end %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<p>
  <strong>Name:</strong>
  <%= @status.user.full_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<% if @status.user == current_user %>
  <%= link_to 'Edit', edit_status_path(@status) %> |
<% end %>

<%= link_to 'Frontpage', statuses_path %> | 
<%= link_to @status.user.full_name + "\'s Profile", user_profile_path(@status.user.profile_name) %>